# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  forestgardener:
    site_hosts:
      - canonical: forestgardener.org.uk
        redirects:
          - www.forestgardener.org.uk
    local_path: ../forestgardener
    repo: git@github.com:growdigital/bedrock-forestgardener.git
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
  growdigital:
    site_hosts:
      - canonical: growdigital.org
        redirects:
          - www.growdigital.org
    local_path: ../growdigital
    repo: git@github.com:growdigital/bedrock-growdigital.git
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: true
  growspace:
    site_hosts:
      - canonical: growspace.org.uk
        redirects:
          - www.growspace.org.uk
    local_path: ../growspace
    repo: git@github.com:growdigital/bedrock-growspace.git
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
  ysgoltrewen:
    site_hosts:
      - canonical: ysgoltrewen.uk
        redirects:
          - www.ysgoltrewen.uk
    local_path: ../ysgoltrewen
    repo: git@github.com:growdigital/bedrock-ysgoltrewen.git
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
